services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: #postgres_user from runtime
      POSTGRES_PASSWORD: #password_password from runtime
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: #user_email from runtime
      PGADMIN_DEFAULT_PASSWORD: #password_password from runtime
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: